{"uid":"8313cd1ef63ca3c2","name":"CP06 - Validar que el usuario sea bloqueado después de cinco intentos fallidos de inicio de sesión.","fullName":"com.demoblaze.tests.LoginTests.testBloqueoTrasCincoIntentosFallidos","historyId":"f921a01f586f41fef54084d0214f865e","time":{"start":1747235339530,"stop":1747235346095,"duration":6565},"status":"failed","statusMessage":"Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]","statusTrace":"java.lang.AssertionError: Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat com.demoblaze.tests.LoginTests.testBloqueoTrasCincoIntentosFallidos(LoginTests.java:81)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)\r\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)\r\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)\r\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)\r\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"setup","time":{"start":1747235338459,"stop":1747235339528,"duration":1069},"description":"","status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"teardown","time":{"start":1747235346097,"stop":1747235346215,"duration":118},"description":"","status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"stepsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"package","value":"com.demoblaze.tests.LoginTests"},{"name":"testClass","value":"com.demoblaze.tests.LoginTests"},{"name":"testMethod","value":"testBloqueoTrasCincoIntentosFallidos"},{"name":"parentSuite","value":"Surefire suite"},{"name":"suite","value":"Surefire test"},{"name":"subSuite","value":"com.demoblaze.tests.LoginTests"},{"name":"host","value":"DENSETSU-XTREME"},{"name":"thread","value":"17056@DENSETSU-XTREME.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Inicio de sesión"},{"name":"epic","value":"Demoblaze"},{"name":"feature","value":"Login"},{"name":"severity","value":"critical"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"578ceaf7e97ee0b1","status":"failed","statusDetails":"Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]","time":{"start":1747235107361,"stop":1747235113905,"duration":6544}},{"uid":"302f035ccf127231","status":"failed","statusDetails":"Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]","time":{"start":1747234109052,"stop":1747234115729,"duration":6677}},{"uid":"5e286c569cf24a98","status":"failed","statusDetails":"Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]","time":{"start":1747233541698,"stop":1747233548240,"duration":6542}},{"uid":"6ea169bcdd23fbe1","status":"failed","statusDetails":"Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]","time":{"start":1747071934584,"stop":1747071941712,"duration":7128}},{"uid":"c2e416655a2b5fdc","status":"failed","statusDetails":"Fallo intencional: el sistema no bloqueó al usuario tras 5 intentos fallidos. expected [true] but found [false]","time":{"start":1746849961145,"stop":1746849967873,"duration":6728}}],"categories":[{"name":"Product defects","matchedStatuses":[]}],"tags":[]},"source":"8313cd1ef63ca3c2.json","parameterValues":[]}